### login admin
POST {{host}}/api/v1/sessions
Content-Type: application/json

{
    "workId": "10000",
    "password": "admin"
}

### login normal user
POST {{host}}/api/v1/sessions
Content-Type: application/json

{
    "workId": 10002,
    "password": "123456"
}

### login fail
POST {{host}}/api/v1/sessions
Content-Type: application/json

{
    "workId": 10000,
    "password": "admin11111"
}

### logout
DELETE {{host}}/api/v1/sessions
Content-Type: application/json

### get all jobs
GET {{host}}/api/v1/jobs
Accept: application/json

### get all permissions
GET {{host}}/api/v1/permissions
Accept: application/json

### list all users
GET {{host}}/api/v1/users?page=1&count=1

### list relics
GET {{host}}/api/v1/relics?name=&page=700&count=20&from=&dateType=&status=1

### add new user
POST {{host}}/api/v1/users
Content-Type: application/json

{
    "workId": 10005,
    "name": "admin",
    "password": "123456",
    "jobId": 5,
    "extraPermissionsId": [
    ],
    "telephone": "5"
}

### update user
PUT {{host}}/api/v1/users/16
Content-Type: application/json

{
    "workId": "aaa",
    "name": "paizhao",
    "password": "",
    "jobId": 1,
    "extraPermissionsId": null,
    "telephone": "13800000001"
}

### delete user
DELETE {{host}}/api/v1/users/13

### list warehouses
GET {{host}}/api/v1/warehouses?page=1&count=50

### list users
GET {{host}}/api/v1/users

### change password
PUT {{host}}/api/v1/users/password
Content-Type: application/json

{
    "oldPassword": "admin111",
    "newPassword": "admin"
}

### create warehouse
POST {{host}}/api/v1/warehouses
Content-Type: application/json

{
    "name": "1"
}

### update warehouse name
PUT {{host}}/api/v1/warehouses/7
Content-Type: application/json

{
    "name": "ddd"
}

### delete warehouse
DELETE {{host}}/api/v1/warehouses/7
Content-Type: application/json

### list relic status
GET {{host}}/api/v1/relics/status

### get relic by id
GET {{host}}/api/v1/relics/1

### change relic info
PUT {{host}}/api/v1/relics/1
Content-Type: application/json

{
    "name": "wdnmd",
    "quantity": 2,
    "year": "南北朝",
    "reign": "xxx",
    "type": "沙雕",
    "source": "xxx捐赠",
    "size": "11cm x 45cm x 14cm",
    "weight": 19198.10,
    "warehouseId": 2,
    "shelfId": 11,
    "place": "aaa",
    "statusId": 5,
    "enterPrice": "0.00",
    "leavePrice": "0.00",
    "comment1": "a",
    "comment2": "b"
}

### list shelf
GET {{host}}/api/v1/shelves?warehouseId=8&name=&page=1&count=20

### add shelf
POST {{host}}/api/v1/shelves
Content-Type: application/json

{
    "warehouseId": 1,
    "name": "aaa"
}

### change shelf
PUT {{host}}/api/v1/shelves/180
Content-Type: application/json

{
    "name": "eaee",
    "warehouseId": 7
}

### delete shelf
DELETE {{host}}/api/v1/shelves/10

### generate data
POST {{host}}/api/test/generate
Content-Type: application/x-www-form-urlencoded

password=wegfan.wegfan&relic=true&shelf=false&warehouse=false

### list relic check
GET {{host}}/api/v1/checks?page=1&count=20

### change relic info
PUT {{host}}/api/v1/relics/1
Content-Type: application/json

{
    "name": "",
    "quantity": "",
    "year": "",
    "reign": "",
    "type": "",
    "source": "",
    "size": "",
    "weight": "",
    "warehouseId": "",
    "shelfId": "",
    "statusId": "",
    "enterPrice": "1.00",
    "leavePrice": "2.55",
    "comment1": "",
    "comment2": ""
}

###