### get all jobs
GET {{host}}/api/v1/jobs
Accept: application/json

### get all permissions
GET {{host}}/api/v1/permissions
Accept: application/json

### list all users
GET {{host}}/api/v1/users

### list relics
GET {{host}}/api/v1/relics?name=1111&page=1&count=4&from=2020-05-04%2001:22:11&type=fix

### add new user
POST {{host}}/api/v1/users
Content-Type: application/json

{
    "workId": 10004,
    "name": "wenzhi",
    "password": "123456",
    "jobId": 1,
    "extraPermissionsId": [
    ],
    "telephone": "4"
}

### update user
PUT {{host}}/api/v1/users/12
Content-Type: application/json

{
    "workId": 10000,
    "name": "admin",
    "password": "admin",
    "jobId": 5,
    "extraPermissionsId": [
    ],
    "telephone": "231312"
}

### delete user
DELETE {{host}}/api/v1/users/13

### list warehouses
GET {{host}}/api/v1/warehouses?page=1&count=50

### login admin
POST {{host}}/api/v1/sessions
Content-Type: application/json

{
    "workId": 10000,
    "password": "admin"
}

### login normal user
POST {{host}}/api/v1/sessions
Content-Type: application/json

{
    "workId": 10004,
    "password": "123456"
}

### login fail
POST {{host}}/api/v1/sessions
Content-Type: application/json

{
    "workId": 10000,
    "password": "admin11111"
}

### logout
DELETE {{host}}/api/v1/sessions
Content-Type: application/json

### list users
GET {{host}}/api/v1/users

### change password
PUT {{host}}/api/v1/users/password
Content-Type: application/json

{
    "oldPassword": "admin111",
    "newPassword": "admin"
}

### create warehouse
POST {{host}}/api/v1/warehouses
Content-Type: application/json

{
    "name": "1"
}

### update warehouse name
PUT {{host}}/api/v1/warehouses/7
Content-Type: application/json

{
    "name": "ddd"
}

### delete warehouse
DELETE {{host}}/api/v1/warehouses/7
Content-Type: application/json

### list relic status
GET {{host}}/api/v1/relics/status

### get relic by id
GET {{host}}/api/v1/relics/1

###