spring:
  profiles:
    active: 'dev'
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'
  mvc:
    date-format: 'yyyy-MM-dd HH:mm:ss'
  servlet:
    multipart:
      max-file-size: '10MB'
      max-request-size: '10MB'
  datasource:
    hikari:
      maximum-pool-size: 100
      max-lifetime: 120000
      connection-timeout: 15000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: false
    default-executor-type: 'reuse'
    auto-mapping-unknown-column-behavior: 'warning'
  global-config:
    db-config:
      id-type: 'auto'
      update-strategy: 'ignored'

logging:
  level:
    cn.wegfan.relicsmanagement: 'info'
  pattern:
    console: '%yellow(%date{${LOG_DATEFORMAT_PATTERN}}) %clr(${LOG_LEVEL_PATTERN}) - [%magenta(%logger)] [%cyan(%file:%line \(%method\))]: %message%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
    file: '%date{${LOG_DATEFORMAT_PATTERN}} ${LOG_LEVEL_PATTERN} - [%logger] [%file:%line \(%method\)] : %message%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
    dateformat: 'yyyy-MM-dd HH:mm:ss.SSS'
  file:
    name: 'data/app.log'
    max-history: 31
    max-size: '1GB'
