### get all jobs
GET {{host}}/api/v1/jobs
Accept: application/json

### list all users
GET {{host}}/api/v1/users

### list relics
GET {{host}}/api/v1/relics?name=1111&page=1&count=4

### add new user
POST {{host}}/api/v1/users
Content-Type: application/json

{
    "workId": 123446,
    "name": "aaa",
    "password": "abc",
    "jobId": 1,
    "permissionId": [1, 2, 3],
    "telephone": "13800138440"
}

### update user
PUT {{host}}/api/v1/users/0x22
Content-Type: application/json

{
    "workId": 122,
    "name": "aaddda",
    "password": "aaaaabc",
    "jobId": 1,
    "permissionId": [
        1
    ],
    "telephone": "231312"
}

### delete user
DELETE {{host}}/api/v1/users/1

### list warehouses
GET {{host}}/api/v1/warehouses?name=dad&page=2&count=1


### test
GET {{host}}/api/v1/tests?workId=123&password=abcdef

###
GET http://127.0.0.1:8081/

###